baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ivy's Lair"
theme = 'cotton-candy-riot'
[menu]
  [[menu.main]]
    identifier = "about"
    name = "Meet the Gremlin"
    url = "/about/"
    weight = 1

    [menu.main.params]
      subtext = "About Me"

  [[menu.main]]
    identifier = "hoard"
    name = "Lore Hoard"
    url = "/hoard/"
    weight = 2

    [menu.main.params]
      subtext = "Samples"

  [[menu.main]]
    identifier = "publications"
    name = "Trophies"
    url = "/publications/"
    weight = 3

    [menu.main.params]
      subtext = "Publications"

  [[menu.main]]
    identifier = "contact"
    name = "Summon Me"
    url = "/contact/"
    weight = 5

    [menu.main.params]
      subtext = "Contact Me"

  [[menu.main]]
    identifier = "blog"
    name = "Inkwell Archives"
    url = "/blog/"
    weight = 4

    [menu.main.params]
      subtext = "Blog"

  [[menu.main]]
    identifier = "ink"
    name = "The Tavern"
    url = "/ink-game/"
    weight = 50

    [menu.main.params]
      subtext = "Ink Sample"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
