baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ivy's Lore Hoard"
theme = 'cotton-candy-riot'
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "desk"
    name = "Ivy's Desk"
    url = "/desk/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "blog"
    name = "Inkwell Archives"
    url = "/blog/"
    weight = 3
